version : '3.8'

services:
  customer-db:
    build: ./Database/customer_db/.
    ports:
      - '30001:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-db:
    build: Database/stations_db/.
    ports:
      - '30002:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-1-db:
    build: Database/station_1_db/.
    ports:
      - '30011:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-2-db:
    build: Database/station_2_db/.
    ports:
      - '30012:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  station-3-db:
    build: Database/station_3_db/.
    ports:
      - '30013:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  queue:
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
